[project]
authors = ["Debarchito Nath <dev.debarchito.nath@protonmail.com>"]
channels = ["conda-forge"]
description = "A text-based adventure game-ish environment to train solo RL agents"
name = "reinforced-shrine-adventure"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
game = "reloadium run -m run --mode game"
check = "ruff check . && pyright"
format = "ruff format ."

[dependencies]
python = "3.11.*"

[pypi-dependencies]
reloadium = ">=1.5.1, <2"
pygame = ">=2.6.1, <3"
bink = ">=0.3.2, <0.4"
pyright = ">=1.1.386, <2"
ruff = ">=0.7.0, <0.8"
