[project]
authors = ["Debarchito Nath <dev.debarchito.nath@protonmail.com>"]
channels = ["conda-forge"]
description = "A text-based adventure game-ish environment to train solo RL agents"
name = "reinforced-shrine-adventure"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
game = "reloadium run -m src"

[dependencies]
python = "3.11.*"
mypy = ">=1.12.0,<2"
ruff = ">=0.6.9,<0.7"
black = ">=24.10.0,<25"

[pypi-dependencies]
reloadium = ">=1.5.1, <2"
pygame = ">=2.6.1, <3"
